allowBuilds:
  "@parcel/watcher": false
  core-js: false
  es5-ext: false
  esbuild: false
  svelte-preprocess: true

engineStrict: true

minimumReleaseAge: 1440

overrides:
  # <0.7.0 has a security vulnerability, 2.0.0 causes issues with SvelteKit
  "cookie@<0.7.0": "^1.0.0"
  esbuild@<=0.24.2: ">=0.25.0"
